# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cole/AyuGram-build/tdesktop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cole/AyuGram-build/tdesktop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cole/AyuGram-build/tdesktop/CMakeFiles /home/cole/AyuGram-build/tdesktop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cole/AyuGram-build/tdesktop/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cole/AyuGram-build/tdesktop/CMakeFiles /home/cole/AyuGram-build/tdesktop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cole/AyuGram-build/tdesktop/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named external_cld3_bundled

# Build rule for target.
external_cld3_bundled: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_cld3_bundled
.PHONY : external_cld3_bundled

# fast build rule for target.
external_cld3_bundled/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/cld3/CMakeFiles/external_cld3_bundled.dir/build.make cmake/external/cld3/CMakeFiles/external_cld3_bundled.dir/build
.PHONY : external_cld3_bundled/fast

#=============================================================================
# Target rules for targets named external_cld3_bundled_feature_extractor.proto

# Build rule for target.
external_cld3_bundled_feature_extractor.proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_cld3_bundled_feature_extractor.proto
.PHONY : external_cld3_bundled_feature_extractor.proto

# fast build rule for target.
external_cld3_bundled_feature_extractor.proto/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/cld3/CMakeFiles/external_cld3_bundled_feature_extractor.proto.dir/build.make cmake/external/cld3/CMakeFiles/external_cld3_bundled_feature_extractor.proto.dir/build
.PHONY : external_cld3_bundled_feature_extractor.proto/fast

#=============================================================================
# Target rules for targets named external_cld3_bundled_sentence.proto

# Build rule for target.
external_cld3_bundled_sentence.proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_cld3_bundled_sentence.proto
.PHONY : external_cld3_bundled_sentence.proto

# fast build rule for target.
external_cld3_bundled_sentence.proto/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/cld3/CMakeFiles/external_cld3_bundled_sentence.proto.dir/build.make cmake/external/cld3/CMakeFiles/external_cld3_bundled_sentence.proto.dir/build
.PHONY : external_cld3_bundled_sentence.proto/fast

#=============================================================================
# Target rules for targets named external_cld3_bundled_task_spec.proto

# Build rule for target.
external_cld3_bundled_task_spec.proto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_cld3_bundled_task_spec.proto
.PHONY : external_cld3_bundled_task_spec.proto

# fast build rule for target.
external_cld3_bundled_task_spec.proto/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/cld3/CMakeFiles/external_cld3_bundled_task_spec.proto.dir/build.make cmake/external/cld3/CMakeFiles/external_cld3_bundled_task_spec.proto.dir/build
.PHONY : external_cld3_bundled_task_spec.proto/fast

#=============================================================================
# Target rules for targets named external_glib_cppgir

# Build rule for target.
external_glib_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_glib_cppgir
.PHONY : external_glib_cppgir

# fast build rule for target.
external_glib_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/glib/CMakeFiles/external_glib_cppgir.dir/build.make cmake/external/glib/CMakeFiles/external_glib_cppgir.dir/build
.PHONY : external_glib_cppgir/fast

#=============================================================================
# Target rules for targets named cppgir

# Build rule for target.
cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppgir
.PHONY : cppgir

# fast build rule for target.
cppgir/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/build.make cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/build
.PHONY : cppgir/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/glib/cppgir/CMakeFiles/examples.dir/build.make cmake/external/glib/cppgir/CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named wrappers

# Build rule for target.
wrappers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wrappers
.PHONY : wrappers

# fast build rule for target.
wrappers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/glib/cppgir/CMakeFiles/wrappers.dir/build.make cmake/external/glib/cppgir/CMakeFiles/wrappers.dir/build
.PHONY : wrappers/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/glib/cppgir/CMakeFiles/uninstall.dir/build.make cmake/external/glib/cppgir/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named external_kcoreaddons_bundled

# Build rule for target.
external_kcoreaddons_bundled: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_kcoreaddons_bundled
.PHONY : external_kcoreaddons_bundled

# fast build rule for target.
external_kcoreaddons_bundled/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/build.make cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/build
.PHONY : external_kcoreaddons_bundled/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins

# Build rule for target.
external_qt_static_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins
.PHONY : external_qt_static_plugins

# fast build rule for target.
external_qt_static_plugins/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/CMakeFiles/external_qt_static_plugins.dir/build.make cmake/external/qt/qt_static_plugins/CMakeFiles/external_qt_static_plugins.dir/build
.PHONY : external_qt_static_plugins/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_kimageformats

# Build rule for target.
external_qt_static_plugins_kimageformats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_kimageformats
.PHONY : external_qt_static_plugins_kimageformats

# fast build rule for target.
external_qt_static_plugins_kimageformats/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/build.make cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/build
.PHONY : external_qt_static_plugins_kimageformats/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_kimageformats_init

# Build rule for target.
external_qt_static_plugins_kimageformats_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_kimageformats_init
.PHONY : external_qt_static_plugins_kimageformats_init

# fast build rule for target.
external_qt_static_plugins_kimageformats_init/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_init.dir/build.make cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_init.dir/build
.PHONY : external_qt_static_plugins_kimageformats_init/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_kimageformats_autogen_timestamp_deps

# Build rule for target.
external_qt_static_plugins_kimageformats_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_kimageformats_autogen_timestamp_deps
.PHONY : external_qt_static_plugins_kimageformats_autogen_timestamp_deps

# fast build rule for target.
external_qt_static_plugins_kimageformats_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_autogen_timestamp_deps.dir/build.make cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_autogen_timestamp_deps.dir/build
.PHONY : external_qt_static_plugins_kimageformats_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_kimageformats_autogen

# Build rule for target.
external_qt_static_plugins_kimageformats_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_kimageformats_autogen
.PHONY : external_qt_static_plugins_kimageformats_autogen

# fast build rule for target.
external_qt_static_plugins_kimageformats_autogen/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_autogen.dir/build.make cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_autogen.dir/build
.PHONY : external_qt_static_plugins_kimageformats_autogen/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_nimf

# Build rule for target.
external_qt_static_plugins_nimf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_nimf
.PHONY : external_qt_static_plugins_nimf

# fast build rule for target.
external_qt_static_plugins_nimf/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf.dir/build.make cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf.dir/build
.PHONY : external_qt_static_plugins_nimf/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_nimf_init

# Build rule for target.
external_qt_static_plugins_nimf_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_nimf_init
.PHONY : external_qt_static_plugins_nimf_init

# fast build rule for target.
external_qt_static_plugins_nimf_init/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_init.dir/build.make cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_init.dir/build
.PHONY : external_qt_static_plugins_nimf_init/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_nimf_autogen_timestamp_deps

# Build rule for target.
external_qt_static_plugins_nimf_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_nimf_autogen_timestamp_deps
.PHONY : external_qt_static_plugins_nimf_autogen_timestamp_deps

# fast build rule for target.
external_qt_static_plugins_nimf_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_autogen_timestamp_deps.dir/build.make cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_autogen_timestamp_deps.dir/build
.PHONY : external_qt_static_plugins_nimf_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_nimf_autogen

# Build rule for target.
external_qt_static_plugins_nimf_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_nimf_autogen
.PHONY : external_qt_static_plugins_nimf_autogen

# fast build rule for target.
external_qt_static_plugins_nimf_autogen/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_autogen.dir/build.make cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_autogen.dir/build
.PHONY : external_qt_static_plugins_nimf_autogen/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5

# Build rule for target.
external_qt_static_plugins_fcitx5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5
.PHONY : external_qt_static_plugins_fcitx5

# fast build rule for target.
external_qt_static_plugins_fcitx5/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/build
.PHONY : external_qt_static_plugins_fcitx5/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5_init

# Build rule for target.
external_qt_static_plugins_fcitx5_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5_init
.PHONY : external_qt_static_plugins_fcitx5_init

# fast build rule for target.
external_qt_static_plugins_fcitx5_init/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_init.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_init.dir/build
.PHONY : external_qt_static_plugins_fcitx5_init/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5_autogen_timestamp_deps

# Build rule for target.
external_qt_static_plugins_fcitx5_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5_autogen_timestamp_deps
.PHONY : external_qt_static_plugins_fcitx5_autogen_timestamp_deps

# fast build rule for target.
external_qt_static_plugins_fcitx5_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_autogen_timestamp_deps.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_autogen_timestamp_deps.dir/build
.PHONY : external_qt_static_plugins_fcitx5_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5_autogen

# Build rule for target.
external_qt_static_plugins_fcitx5_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5_autogen
.PHONY : external_qt_static_plugins_fcitx5_autogen

# fast build rule for target.
external_qt_static_plugins_fcitx5_autogen/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_autogen.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_autogen.dir/build
.PHONY : external_qt_static_plugins_fcitx5_autogen/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5_dbusaddons

# Build rule for target.
external_qt_static_plugins_fcitx5_dbusaddons: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5_dbusaddons
.PHONY : external_qt_static_plugins_fcitx5_dbusaddons

# fast build rule for target.
external_qt_static_plugins_fcitx5_dbusaddons/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/build
.PHONY : external_qt_static_plugins_fcitx5_dbusaddons/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps

# Build rule for target.
external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps
.PHONY : external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps

# fast build rule for target.
external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps.dir/build
.PHONY : external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_fcitx5_dbusaddons_autogen

# Build rule for target.
external_qt_static_plugins_fcitx5_dbusaddons_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_fcitx5_dbusaddons_autogen
.PHONY : external_qt_static_plugins_fcitx5_dbusaddons_autogen

# fast build rule for target.
external_qt_static_plugins_fcitx5_dbusaddons_autogen/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons_autogen.dir/build.make cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons_autogen.dir/build
.PHONY : external_qt_static_plugins_fcitx5_dbusaddons_autogen/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_hime

# Build rule for target.
external_qt_static_plugins_hime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_hime
.PHONY : external_qt_static_plugins_hime

# fast build rule for target.
external_qt_static_plugins_hime/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime.dir/build.make cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime.dir/build
.PHONY : external_qt_static_plugins_hime/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_hime_init

# Build rule for target.
external_qt_static_plugins_hime_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_hime_init
.PHONY : external_qt_static_plugins_hime_init

# fast build rule for target.
external_qt_static_plugins_hime_init/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_init.dir/build.make cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_init.dir/build
.PHONY : external_qt_static_plugins_hime_init/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_hime_autogen_timestamp_deps

# Build rule for target.
external_qt_static_plugins_hime_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_hime_autogen_timestamp_deps
.PHONY : external_qt_static_plugins_hime_autogen_timestamp_deps

# fast build rule for target.
external_qt_static_plugins_hime_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_autogen_timestamp_deps.dir/build.make cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_autogen_timestamp_deps.dir/build
.PHONY : external_qt_static_plugins_hime_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_hime_autogen

# Build rule for target.
external_qt_static_plugins_hime_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_hime_autogen
.PHONY : external_qt_static_plugins_hime_autogen

# fast build rule for target.
external_qt_static_plugins_hime_autogen/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_autogen.dir/build.make cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_autogen.dir/build
.PHONY : external_qt_static_plugins_hime_autogen/fast

#=============================================================================
# Target rules for targets named external_qt_static_plugins_hime_im_client

# Build rule for target.
external_qt_static_plugins_hime_im_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qt_static_plugins_hime_im_client
.PHONY : external_qt_static_plugins_hime_im_client

# fast build rule for target.
external_qt_static_plugins_hime_im_client/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qt/qt_static_plugins/hime/hime_im_client/CMakeFiles/external_qt_static_plugins_hime_im_client.dir/build.make cmake/external/qt/qt_static_plugins/hime/hime_im_client/CMakeFiles/external_qt_static_plugins_hime_im_client.dir/build
.PHONY : external_qt_static_plugins_hime_im_client/fast

#=============================================================================
# Target rules for targets named external_qr_code_generator_bundled

# Build rule for target.
external_qr_code_generator_bundled: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_qr_code_generator_bundled
.PHONY : external_qr_code_generator_bundled

# fast build rule for target.
external_qr_code_generator_bundled/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/qr_code_generator/CMakeFiles/external_qr_code_generator_bundled.dir/build.make cmake/external/qr_code_generator/CMakeFiles/external_qr_code_generator_bundled.dir/build
.PHONY : external_qr_code_generator_bundled/fast

#=============================================================================
# Target rules for targets named external_rlottie_bundled

# Build rule for target.
external_rlottie_bundled: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 external_rlottie_bundled
.PHONY : external_rlottie_bundled

# fast build rule for target.
external_rlottie_bundled/fast:
	$(MAKE) $(MAKESILENT) -f cmake/external/rlottie/CMakeFiles/external_rlottie_bundled.dir/build.make cmake/external/rlottie/CMakeFiles/external_rlottie_bundled.dir/build
.PHONY : external_rlottie_bundled/fast

#=============================================================================
# Target rules for targets named Telegram

# Build rule for target.
Telegram: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram
.PHONY : Telegram

# fast build rule for target.
Telegram/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram.dir/build.make Telegram/CMakeFiles/Telegram.dir/build
.PHONY : Telegram/fast

#=============================================================================
# Target rules for targets named lib_ffmpeg

# Build rule for target.
lib_ffmpeg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ffmpeg
.PHONY : lib_ffmpeg

# fast build rule for target.
lib_ffmpeg/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/lib_ffmpeg.dir/build.make Telegram/CMakeFiles/lib_ffmpeg.dir/build
.PHONY : lib_ffmpeg/fast

#=============================================================================
# Target rules for targets named lib_stripe

# Build rule for target.
lib_stripe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_stripe
.PHONY : lib_stripe

# fast build rule for target.
lib_stripe/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/lib_stripe.dir/build.make Telegram/CMakeFiles/lib_stripe.dir/build
.PHONY : lib_stripe/fast

#=============================================================================
# Target rules for targets named lib_tgcalls

# Build rule for target.
lib_tgcalls: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_tgcalls
.PHONY : lib_tgcalls

# fast build rule for target.
lib_tgcalls/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/lib_tgcalls.dir/build.make Telegram/CMakeFiles/lib_tgcalls.dir/build
.PHONY : lib_tgcalls/fast

#=============================================================================
# Target rules for targets named lib_prisma

# Build rule for target.
lib_prisma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_prisma
.PHONY : lib_prisma

# fast build rule for target.
lib_prisma/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/lib_prisma.dir/build.make Telegram/CMakeFiles/lib_prisma.dir/build
.PHONY : lib_prisma/fast

#=============================================================================
# Target rules for targets named td_export

# Build rule for target.
td_export: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_export
.PHONY : td_export

# fast build rule for target.
td_export/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_export.dir/build.make Telegram/CMakeFiles/td_export.dir/build
.PHONY : td_export/fast

#=============================================================================
# Target rules for targets named td_iv

# Build rule for target.
td_iv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_iv
.PHONY : td_iv

# fast build rule for target.
td_iv/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_iv.dir/build.make Telegram/CMakeFiles/td_iv.dir/build
.PHONY : td_iv/fast

#=============================================================================
# Target rules for targets named td_lang

# Build rule for target.
td_lang: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_lang
.PHONY : td_lang

# fast build rule for target.
td_lang/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_lang.dir/build.make Telegram/CMakeFiles/td_lang.dir/build
.PHONY : td_lang/fast

#=============================================================================
# Target rules for targets named td_lang_lang

# Build rule for target.
td_lang_lang: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_lang_lang
.PHONY : td_lang_lang

# fast build rule for target.
td_lang_lang/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_lang_lang.dir/build.make Telegram/CMakeFiles/td_lang_lang.dir/build
.PHONY : td_lang_lang/fast

#=============================================================================
# Target rules for targets named td_mtproto

# Build rule for target.
td_mtproto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_mtproto
.PHONY : td_mtproto

# fast build rule for target.
td_mtproto/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_mtproto.dir/build.make Telegram/CMakeFiles/td_mtproto.dir/build
.PHONY : td_mtproto/fast

#=============================================================================
# Target rules for targets named td_scheme

# Build rule for target.
td_scheme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_scheme
.PHONY : td_scheme

# fast build rule for target.
td_scheme/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_scheme.dir/build.make Telegram/CMakeFiles/td_scheme.dir/build
.PHONY : td_scheme/fast

#=============================================================================
# Target rules for targets named td_scheme_scheme

# Build rule for target.
td_scheme_scheme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_scheme_scheme
.PHONY : td_scheme_scheme

# fast build rule for target.
td_scheme_scheme/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_scheme_scheme.dir/build.make Telegram/CMakeFiles/td_scheme_scheme.dir/build
.PHONY : td_scheme_scheme/fast

#=============================================================================
# Target rules for targets named td_tde2e

# Build rule for target.
td_tde2e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_tde2e
.PHONY : td_tde2e

# fast build rule for target.
td_tde2e/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_tde2e.dir/build.make Telegram/CMakeFiles/td_tde2e.dir/build
.PHONY : td_tde2e/fast

#=============================================================================
# Target rules for targets named td_ui

# Build rule for target.
td_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_ui
.PHONY : td_ui

# fast build rule for target.
td_ui/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_ui.dir/build.make Telegram/CMakeFiles/td_ui.dir/build
.PHONY : td_ui/fast

#=============================================================================
# Target rules for targets named td_ui_styles

# Build rule for target.
td_ui_styles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 td_ui_styles
.PHONY : td_ui_styles

# fast build rule for target.
td_ui_styles/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/td_ui_styles.dir/build.make Telegram/CMakeFiles/td_ui_styles.dir/build
.PHONY : td_ui_styles/fast

#=============================================================================
# Target rules for targets named Telegram_XdpBackground_dbus

# Build rule for target.
Telegram_XdpBackground_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdpBackground_dbus
.PHONY : Telegram_XdpBackground_dbus

# fast build rule for target.
Telegram_XdpBackground_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdpBackground_dbus.dir/build.make Telegram/CMakeFiles/Telegram_XdpBackground_dbus.dir/build
.PHONY : Telegram_XdpBackground_dbus/fast

#=============================================================================
# Target rules for targets named Telegram_XdpBackground_dbus_timestamp

# Build rule for target.
Telegram_XdpBackground_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdpBackground_dbus_timestamp
.PHONY : Telegram_XdpBackground_dbus_timestamp

# fast build rule for target.
Telegram_XdpBackground_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdpBackground_dbus_timestamp.dir/build.make Telegram/CMakeFiles/Telegram_XdpBackground_dbus_timestamp.dir/build
.PHONY : Telegram_XdpBackground_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named Telegram_XdpBackground_gir

# Build rule for target.
Telegram_XdpBackground_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdpBackground_gir
.PHONY : Telegram_XdpBackground_gir

# fast build rule for target.
Telegram_XdpBackground_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdpBackground_gir.dir/build.make Telegram/CMakeFiles/Telegram_XdpBackground_gir.dir/build
.PHONY : Telegram_XdpBackground_gir/fast

#=============================================================================
# Target rules for targets named Telegram_XdpBackground_cppgir

# Build rule for target.
Telegram_XdpBackground_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdpBackground_cppgir
.PHONY : Telegram_XdpBackground_cppgir

# fast build rule for target.
Telegram_XdpBackground_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdpBackground_cppgir.dir/build.make Telegram/CMakeFiles/Telegram_XdpBackground_cppgir.dir/build
.PHONY : Telegram_XdpBackground_cppgir/fast

#=============================================================================
# Target rules for targets named Telegram_XdgNotifications_dbus

# Build rule for target.
Telegram_XdgNotifications_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdgNotifications_dbus
.PHONY : Telegram_XdgNotifications_dbus

# fast build rule for target.
Telegram_XdgNotifications_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdgNotifications_dbus.dir/build.make Telegram/CMakeFiles/Telegram_XdgNotifications_dbus.dir/build
.PHONY : Telegram_XdgNotifications_dbus/fast

#=============================================================================
# Target rules for targets named Telegram_XdgNotifications_dbus_timestamp

# Build rule for target.
Telegram_XdgNotifications_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdgNotifications_dbus_timestamp
.PHONY : Telegram_XdgNotifications_dbus_timestamp

# fast build rule for target.
Telegram_XdgNotifications_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdgNotifications_dbus_timestamp.dir/build.make Telegram/CMakeFiles/Telegram_XdgNotifications_dbus_timestamp.dir/build
.PHONY : Telegram_XdgNotifications_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named Telegram_XdgNotifications_gir

# Build rule for target.
Telegram_XdgNotifications_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdgNotifications_gir
.PHONY : Telegram_XdgNotifications_gir

# fast build rule for target.
Telegram_XdgNotifications_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdgNotifications_gir.dir/build.make Telegram/CMakeFiles/Telegram_XdgNotifications_gir.dir/build
.PHONY : Telegram_XdgNotifications_gir/fast

#=============================================================================
# Target rules for targets named Telegram_XdgNotifications_cppgir

# Build rule for target.
Telegram_XdgNotifications_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_XdgNotifications_cppgir
.PHONY : Telegram_XdgNotifications_cppgir

# fast build rule for target.
Telegram_XdgNotifications_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_XdgNotifications_cppgir.dir/build.make Telegram/CMakeFiles/Telegram_XdgNotifications_cppgir.dir/build
.PHONY : Telegram_XdgNotifications_cppgir/fast

#=============================================================================
# Target rules for targets named Telegram_appstream_changelog

# Build rule for target.
Telegram_appstream_changelog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_appstream_changelog
.PHONY : Telegram_appstream_changelog

# fast build rule for target.
Telegram_appstream_changelog/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_appstream_changelog.dir/build.make Telegram/CMakeFiles/Telegram_appstream_changelog.dir/build
.PHONY : Telegram_appstream_changelog/fast

#=============================================================================
# Target rules for targets named Telegram_qmlimportscan

# Build rule for target.
Telegram_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_qmlimportscan
.PHONY : Telegram_qmlimportscan

# fast build rule for target.
Telegram_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_qmlimportscan.dir/build.make Telegram/CMakeFiles/Telegram_qmlimportscan.dir/build
.PHONY : Telegram_qmlimportscan/fast

#=============================================================================
# Target rules for targets named Telegram_autogen_timestamp_deps

# Build rule for target.
Telegram_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_autogen_timestamp_deps
.PHONY : Telegram_autogen_timestamp_deps

# fast build rule for target.
Telegram_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_autogen_timestamp_deps.dir/build.make Telegram/CMakeFiles/Telegram_autogen_timestamp_deps.dir/build
.PHONY : Telegram_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Telegram_autogen

# Build rule for target.
Telegram_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Telegram_autogen
.PHONY : Telegram_autogen

# fast build rule for target.
Telegram_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/CMakeFiles/Telegram_autogen.dir/build.make Telegram/CMakeFiles/Telegram_autogen.dir/build
.PHONY : Telegram_autogen/fast

#=============================================================================
# Target rules for targets named lib_crl

# Build rule for target.
lib_crl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_crl
.PHONY : lib_crl

# fast build rule for target.
lib_crl/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_crl/CMakeFiles/lib_crl.dir/build.make Telegram/lib_crl/CMakeFiles/lib_crl.dir/build
.PHONY : lib_crl/fast

#=============================================================================
# Target rules for targets named lib_base

# Build rule for target.
lib_base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base
.PHONY : lib_base

# fast build rule for target.
lib_base/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base.dir/build.make Telegram/lib_base/CMakeFiles/lib_base.dir/build
.PHONY : lib_base/fast

#=============================================================================
# Target rules for targets named lib_base_crash_report_writer

# Build rule for target.
lib_base_crash_report_writer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_crash_report_writer
.PHONY : lib_base_crash_report_writer

# fast build rule for target.
lib_base_crash_report_writer/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_crash_report_writer.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_crash_report_writer.dir/build
.PHONY : lib_base_crash_report_writer/fast

#=============================================================================
# Target rules for targets named lib_base_XdgDBus_dbus

# Build rule for target.
lib_base_XdgDBus_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgDBus_dbus
.PHONY : lib_base_XdgDBus_dbus

# fast build rule for target.
lib_base_XdgDBus_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_dbus.dir/build
.PHONY : lib_base_XdgDBus_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_XdgDBus_dbus_timestamp

# Build rule for target.
lib_base_XdgDBus_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgDBus_dbus_timestamp
.PHONY : lib_base_XdgDBus_dbus_timestamp

# fast build rule for target.
lib_base_XdgDBus_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_dbus_timestamp.dir/build
.PHONY : lib_base_XdgDBus_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_XdgDBus_gir

# Build rule for target.
lib_base_XdgDBus_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgDBus_gir
.PHONY : lib_base_XdgDBus_gir

# fast build rule for target.
lib_base_XdgDBus_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_gir.dir/build
.PHONY : lib_base_XdgDBus_gir/fast

#=============================================================================
# Target rules for targets named lib_base_XdgDBus_cppgir

# Build rule for target.
lib_base_XdgDBus_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgDBus_cppgir
.PHONY : lib_base_XdgDBus_cppgir

# fast build rule for target.
lib_base_XdgDBus_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_cppgir.dir/build
.PHONY : lib_base_XdgDBus_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpInhibit_dbus

# Build rule for target.
lib_base_XdpInhibit_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpInhibit_dbus
.PHONY : lib_base_XdpInhibit_dbus

# fast build rule for target.
lib_base_XdpInhibit_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_dbus.dir/build
.PHONY : lib_base_XdpInhibit_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_XdpInhibit_dbus_timestamp

# Build rule for target.
lib_base_XdpInhibit_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpInhibit_dbus_timestamp
.PHONY : lib_base_XdpInhibit_dbus_timestamp

# fast build rule for target.
lib_base_XdpInhibit_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_dbus_timestamp.dir/build
.PHONY : lib_base_XdpInhibit_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_XdpInhibit_gir

# Build rule for target.
lib_base_XdpInhibit_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpInhibit_gir
.PHONY : lib_base_XdpInhibit_gir

# fast build rule for target.
lib_base_XdpInhibit_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_gir.dir/build
.PHONY : lib_base_XdpInhibit_gir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpInhibit_cppgir

# Build rule for target.
lib_base_XdpInhibit_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpInhibit_cppgir
.PHONY : lib_base_XdpInhibit_cppgir

# fast build rule for target.
lib_base_XdpInhibit_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_cppgir.dir/build
.PHONY : lib_base_XdpInhibit_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpOpenURI_dbus

# Build rule for target.
lib_base_XdpOpenURI_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpOpenURI_dbus
.PHONY : lib_base_XdpOpenURI_dbus

# fast build rule for target.
lib_base_XdpOpenURI_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_dbus.dir/build
.PHONY : lib_base_XdpOpenURI_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_XdpOpenURI_dbus_timestamp

# Build rule for target.
lib_base_XdpOpenURI_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpOpenURI_dbus_timestamp
.PHONY : lib_base_XdpOpenURI_dbus_timestamp

# fast build rule for target.
lib_base_XdpOpenURI_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_dbus_timestamp.dir/build
.PHONY : lib_base_XdpOpenURI_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_XdpOpenURI_gir

# Build rule for target.
lib_base_XdpOpenURI_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpOpenURI_gir
.PHONY : lib_base_XdpOpenURI_gir

# fast build rule for target.
lib_base_XdpOpenURI_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_gir.dir/build
.PHONY : lib_base_XdpOpenURI_gir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpOpenURI_cppgir

# Build rule for target.
lib_base_XdpOpenURI_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpOpenURI_cppgir
.PHONY : lib_base_XdpOpenURI_cppgir

# fast build rule for target.
lib_base_XdpOpenURI_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_cppgir.dir/build
.PHONY : lib_base_XdpOpenURI_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpRequest_dbus

# Build rule for target.
lib_base_XdpRequest_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpRequest_dbus
.PHONY : lib_base_XdpRequest_dbus

# fast build rule for target.
lib_base_XdpRequest_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_dbus.dir/build
.PHONY : lib_base_XdpRequest_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_XdpRequest_dbus_timestamp

# Build rule for target.
lib_base_XdpRequest_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpRequest_dbus_timestamp
.PHONY : lib_base_XdpRequest_dbus_timestamp

# fast build rule for target.
lib_base_XdpRequest_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_dbus_timestamp.dir/build
.PHONY : lib_base_XdpRequest_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_XdpRequest_gir

# Build rule for target.
lib_base_XdpRequest_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpRequest_gir
.PHONY : lib_base_XdpRequest_gir

# fast build rule for target.
lib_base_XdpRequest_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_gir.dir/build
.PHONY : lib_base_XdpRequest_gir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpRequest_cppgir

# Build rule for target.
lib_base_XdpRequest_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpRequest_cppgir
.PHONY : lib_base_XdpRequest_cppgir

# fast build rule for target.
lib_base_XdpRequest_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_cppgir.dir/build
.PHONY : lib_base_XdpRequest_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpSettings_dbus

# Build rule for target.
lib_base_XdpSettings_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpSettings_dbus
.PHONY : lib_base_XdpSettings_dbus

# fast build rule for target.
lib_base_XdpSettings_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_dbus.dir/build
.PHONY : lib_base_XdpSettings_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_XdpSettings_dbus_timestamp

# Build rule for target.
lib_base_XdpSettings_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpSettings_dbus_timestamp
.PHONY : lib_base_XdpSettings_dbus_timestamp

# fast build rule for target.
lib_base_XdpSettings_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_dbus_timestamp.dir/build
.PHONY : lib_base_XdpSettings_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_XdpSettings_gir

# Build rule for target.
lib_base_XdpSettings_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpSettings_gir
.PHONY : lib_base_XdpSettings_gir

# fast build rule for target.
lib_base_XdpSettings_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_gir.dir/build
.PHONY : lib_base_XdpSettings_gir/fast

#=============================================================================
# Target rules for targets named lib_base_XdpSettings_cppgir

# Build rule for target.
lib_base_XdpSettings_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdpSettings_cppgir
.PHONY : lib_base_XdpSettings_cppgir

# fast build rule for target.
lib_base_XdpSettings_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_cppgir.dir/build
.PHONY : lib_base_XdpSettings_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_XdgFileManager1_dbus

# Build rule for target.
lib_base_XdgFileManager1_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgFileManager1_dbus
.PHONY : lib_base_XdgFileManager1_dbus

# fast build rule for target.
lib_base_XdgFileManager1_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_dbus.dir/build
.PHONY : lib_base_XdgFileManager1_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_XdgFileManager1_dbus_timestamp

# Build rule for target.
lib_base_XdgFileManager1_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgFileManager1_dbus_timestamp
.PHONY : lib_base_XdgFileManager1_dbus_timestamp

# fast build rule for target.
lib_base_XdgFileManager1_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_dbus_timestamp.dir/build
.PHONY : lib_base_XdgFileManager1_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_XdgFileManager1_gir

# Build rule for target.
lib_base_XdgFileManager1_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgFileManager1_gir
.PHONY : lib_base_XdgFileManager1_gir

# fast build rule for target.
lib_base_XdgFileManager1_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_gir.dir/build
.PHONY : lib_base_XdgFileManager1_gir/fast

#=============================================================================
# Target rules for targets named lib_base_XdgFileManager1_cppgir

# Build rule for target.
lib_base_XdgFileManager1_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_XdgFileManager1_cppgir
.PHONY : lib_base_XdgFileManager1_cppgir

# fast build rule for target.
lib_base_XdgFileManager1_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_cppgir.dir/build
.PHONY : lib_base_XdgFileManager1_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_MutterIdleMonitor_dbus

# Build rule for target.
lib_base_MutterIdleMonitor_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_MutterIdleMonitor_dbus
.PHONY : lib_base_MutterIdleMonitor_dbus

# fast build rule for target.
lib_base_MutterIdleMonitor_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_dbus.dir/build
.PHONY : lib_base_MutterIdleMonitor_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_MutterIdleMonitor_dbus_timestamp

# Build rule for target.
lib_base_MutterIdleMonitor_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_MutterIdleMonitor_dbus_timestamp
.PHONY : lib_base_MutterIdleMonitor_dbus_timestamp

# fast build rule for target.
lib_base_MutterIdleMonitor_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_dbus_timestamp.dir/build
.PHONY : lib_base_MutterIdleMonitor_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_MutterIdleMonitor_gir

# Build rule for target.
lib_base_MutterIdleMonitor_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_MutterIdleMonitor_gir
.PHONY : lib_base_MutterIdleMonitor_gir

# fast build rule for target.
lib_base_MutterIdleMonitor_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_gir.dir/build
.PHONY : lib_base_MutterIdleMonitor_gir/fast

#=============================================================================
# Target rules for targets named lib_base_MutterIdleMonitor_cppgir

# Build rule for target.
lib_base_MutterIdleMonitor_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_MutterIdleMonitor_cppgir
.PHONY : lib_base_MutterIdleMonitor_cppgir

# fast build rule for target.
lib_base_MutterIdleMonitor_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_cppgir.dir/build
.PHONY : lib_base_MutterIdleMonitor_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_SigxcpuFeedback_dbus

# Build rule for target.
lib_base_SigxcpuFeedback_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_SigxcpuFeedback_dbus
.PHONY : lib_base_SigxcpuFeedback_dbus

# fast build rule for target.
lib_base_SigxcpuFeedback_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_dbus.dir/build
.PHONY : lib_base_SigxcpuFeedback_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_SigxcpuFeedback_dbus_timestamp

# Build rule for target.
lib_base_SigxcpuFeedback_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_SigxcpuFeedback_dbus_timestamp
.PHONY : lib_base_SigxcpuFeedback_dbus_timestamp

# fast build rule for target.
lib_base_SigxcpuFeedback_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_dbus_timestamp.dir/build
.PHONY : lib_base_SigxcpuFeedback_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_SigxcpuFeedback_gir

# Build rule for target.
lib_base_SigxcpuFeedback_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_SigxcpuFeedback_gir
.PHONY : lib_base_SigxcpuFeedback_gir

# fast build rule for target.
lib_base_SigxcpuFeedback_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_gir.dir/build
.PHONY : lib_base_SigxcpuFeedback_gir/fast

#=============================================================================
# Target rules for targets named lib_base_SigxcpuFeedback_cppgir

# Build rule for target.
lib_base_SigxcpuFeedback_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_SigxcpuFeedback_cppgir
.PHONY : lib_base_SigxcpuFeedback_cppgir

# fast build rule for target.
lib_base_SigxcpuFeedback_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_cppgir.dir/build
.PHONY : lib_base_SigxcpuFeedback_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_Mpris_dbus

# Build rule for target.
lib_base_Mpris_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Mpris_dbus
.PHONY : lib_base_Mpris_dbus

# fast build rule for target.
lib_base_Mpris_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Mpris_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Mpris_dbus.dir/build
.PHONY : lib_base_Mpris_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_Mpris_dbus_timestamp

# Build rule for target.
lib_base_Mpris_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Mpris_dbus_timestamp
.PHONY : lib_base_Mpris_dbus_timestamp

# fast build rule for target.
lib_base_Mpris_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Mpris_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Mpris_dbus_timestamp.dir/build
.PHONY : lib_base_Mpris_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_Mpris_gir

# Build rule for target.
lib_base_Mpris_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Mpris_gir
.PHONY : lib_base_Mpris_gir

# fast build rule for target.
lib_base_Mpris_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Mpris_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Mpris_gir.dir/build
.PHONY : lib_base_Mpris_gir/fast

#=============================================================================
# Target rules for targets named lib_base_Mpris_cppgir

# Build rule for target.
lib_base_Mpris_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Mpris_cppgir
.PHONY : lib_base_Mpris_cppgir

# fast build rule for target.
lib_base_Mpris_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Mpris_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Mpris_cppgir.dir/build
.PHONY : lib_base_Mpris_cppgir/fast

#=============================================================================
# Target rules for targets named lib_base_Snapcraft_dbus

# Build rule for target.
lib_base_Snapcraft_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Snapcraft_dbus
.PHONY : lib_base_Snapcraft_dbus

# fast build rule for target.
lib_base_Snapcraft_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_dbus.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_dbus.dir/build
.PHONY : lib_base_Snapcraft_dbus/fast

#=============================================================================
# Target rules for targets named lib_base_Snapcraft_dbus_timestamp

# Build rule for target.
lib_base_Snapcraft_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Snapcraft_dbus_timestamp
.PHONY : lib_base_Snapcraft_dbus_timestamp

# fast build rule for target.
lib_base_Snapcraft_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_dbus_timestamp.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_dbus_timestamp.dir/build
.PHONY : lib_base_Snapcraft_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_base_Snapcraft_gir

# Build rule for target.
lib_base_Snapcraft_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Snapcraft_gir
.PHONY : lib_base_Snapcraft_gir

# fast build rule for target.
lib_base_Snapcraft_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_gir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_gir.dir/build
.PHONY : lib_base_Snapcraft_gir/fast

#=============================================================================
# Target rules for targets named lib_base_Snapcraft_cppgir

# Build rule for target.
lib_base_Snapcraft_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_base_Snapcraft_cppgir
.PHONY : lib_base_Snapcraft_cppgir

# fast build rule for target.
lib_base_Snapcraft_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_cppgir.dir/build.make Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_cppgir.dir/build
.PHONY : lib_base_Snapcraft_cppgir/fast

#=============================================================================
# Target rules for targets named lib_ui

# Build rule for target.
lib_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ui
.PHONY : lib_ui

# fast build rule for target.
lib_ui/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_ui/CMakeFiles/lib_ui.dir/build.make Telegram/lib_ui/CMakeFiles/lib_ui.dir/build
.PHONY : lib_ui/fast

#=============================================================================
# Target rules for targets named lib_ui_palette

# Build rule for target.
lib_ui_palette: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ui_palette
.PHONY : lib_ui_palette

# fast build rule for target.
lib_ui_palette/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_ui/CMakeFiles/lib_ui_palette.dir/build.make Telegram/lib_ui/CMakeFiles/lib_ui_palette.dir/build
.PHONY : lib_ui_palette/fast

#=============================================================================
# Target rules for targets named lib_ui_styles

# Build rule for target.
lib_ui_styles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ui_styles
.PHONY : lib_ui_styles

# fast build rule for target.
lib_ui_styles/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_ui/CMakeFiles/lib_ui_styles.dir/build.make Telegram/lib_ui/CMakeFiles/lib_ui_styles.dir/build
.PHONY : lib_ui_styles/fast

#=============================================================================
# Target rules for targets named lib_ui_emoji

# Build rule for target.
lib_ui_emoji: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ui_emoji
.PHONY : lib_ui_emoji

# fast build rule for target.
lib_ui_emoji/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_ui/CMakeFiles/lib_ui_emoji.dir/build.make Telegram/lib_ui/CMakeFiles/lib_ui_emoji.dir/build
.PHONY : lib_ui_emoji/fast

#=============================================================================
# Target rules for targets named lib_ui_autogen_timestamp_deps

# Build rule for target.
lib_ui_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ui_autogen_timestamp_deps
.PHONY : lib_ui_autogen_timestamp_deps

# fast build rule for target.
lib_ui_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_ui/CMakeFiles/lib_ui_autogen_timestamp_deps.dir/build.make Telegram/lib_ui/CMakeFiles/lib_ui_autogen_timestamp_deps.dir/build
.PHONY : lib_ui_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named lib_ui_autogen

# Build rule for target.
lib_ui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_ui_autogen
.PHONY : lib_ui_autogen

# fast build rule for target.
lib_ui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_ui/CMakeFiles/lib_ui_autogen.dir/build.make Telegram/lib_ui/CMakeFiles/lib_ui_autogen.dir/build
.PHONY : lib_ui_autogen/fast

#=============================================================================
# Target rules for targets named lib_tl

# Build rule for target.
lib_tl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_tl
.PHONY : lib_tl

# fast build rule for target.
lib_tl/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_tl/CMakeFiles/lib_tl.dir/build.make Telegram/lib_tl/CMakeFiles/lib_tl.dir/build
.PHONY : lib_tl/fast

#=============================================================================
# Target rules for targets named lib_spellcheck

# Build rule for target.
lib_spellcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_spellcheck
.PHONY : lib_spellcheck

# fast build rule for target.
lib_spellcheck/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_spellcheck/CMakeFiles/lib_spellcheck.dir/build.make Telegram/lib_spellcheck/CMakeFiles/lib_spellcheck.dir/build
.PHONY : lib_spellcheck/fast

#=============================================================================
# Target rules for targets named lib_storage

# Build rule for target.
lib_storage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_storage
.PHONY : lib_storage

# fast build rule for target.
lib_storage/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_storage/CMakeFiles/lib_storage.dir/build.make Telegram/lib_storage/CMakeFiles/lib_storage.dir/build
.PHONY : lib_storage/fast

#=============================================================================
# Target rules for targets named lib_lottie

# Build rule for target.
lib_lottie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_lottie
.PHONY : lib_lottie

# fast build rule for target.
lib_lottie/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/build.make Telegram/lib_lottie/CMakeFiles/lib_lottie.dir/build
.PHONY : lib_lottie/fast

#=============================================================================
# Target rules for targets named lib_qr

# Build rule for target.
lib_qr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_qr
.PHONY : lib_qr

# fast build rule for target.
lib_qr/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_qr/CMakeFiles/lib_qr.dir/build.make Telegram/lib_qr/CMakeFiles/lib_qr.dir/build
.PHONY : lib_qr/fast

#=============================================================================
# Target rules for targets named lib_webrtc

# Build rule for target.
lib_webrtc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_webrtc
.PHONY : lib_webrtc

# fast build rule for target.
lib_webrtc/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_webrtc/CMakeFiles/lib_webrtc.dir/build.make Telegram/lib_webrtc/CMakeFiles/lib_webrtc.dir/build
.PHONY : lib_webrtc/fast

#=============================================================================
# Target rules for targets named lib_webview

# Build rule for target.
lib_webview: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_webview
.PHONY : lib_webview

# fast build rule for target.
lib_webview/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_webview/CMakeFiles/lib_webview.dir/build.make Telegram/lib_webview/CMakeFiles/lib_webview.dir/build
.PHONY : lib_webview/fast

#=============================================================================
# Target rules for targets named lib_webview_Webview_dbus

# Build rule for target.
lib_webview_Webview_dbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_webview_Webview_dbus
.PHONY : lib_webview_Webview_dbus

# fast build rule for target.
lib_webview_Webview_dbus/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_webview/CMakeFiles/lib_webview_Webview_dbus.dir/build.make Telegram/lib_webview/CMakeFiles/lib_webview_Webview_dbus.dir/build
.PHONY : lib_webview_Webview_dbus/fast

#=============================================================================
# Target rules for targets named lib_webview_Webview_dbus_timestamp

# Build rule for target.
lib_webview_Webview_dbus_timestamp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_webview_Webview_dbus_timestamp
.PHONY : lib_webview_Webview_dbus_timestamp

# fast build rule for target.
lib_webview_Webview_dbus_timestamp/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_webview/CMakeFiles/lib_webview_Webview_dbus_timestamp.dir/build.make Telegram/lib_webview/CMakeFiles/lib_webview_Webview_dbus_timestamp.dir/build
.PHONY : lib_webview_Webview_dbus_timestamp/fast

#=============================================================================
# Target rules for targets named lib_webview_Webview_gir

# Build rule for target.
lib_webview_Webview_gir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_webview_Webview_gir
.PHONY : lib_webview_Webview_gir

# fast build rule for target.
lib_webview_Webview_gir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_webview/CMakeFiles/lib_webview_Webview_gir.dir/build.make Telegram/lib_webview/CMakeFiles/lib_webview_Webview_gir.dir/build
.PHONY : lib_webview_Webview_gir/fast

#=============================================================================
# Target rules for targets named lib_webview_Webview_cppgir

# Build rule for target.
lib_webview_Webview_cppgir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_webview_Webview_cppgir
.PHONY : lib_webview_Webview_cppgir

# fast build rule for target.
lib_webview_Webview_cppgir/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_webview/CMakeFiles/lib_webview_Webview_cppgir.dir/build.make Telegram/lib_webview/CMakeFiles/lib_webview_Webview_cppgir.dir/build
.PHONY : lib_webview_Webview_cppgir/fast

#=============================================================================
# Target rules for targets named codegen_common

# Build rule for target.
codegen_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_common
.PHONY : codegen_common

# fast build rule for target.
codegen_common/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/build.make Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/build
.PHONY : codegen_common/fast

#=============================================================================
# Target rules for targets named codegen_emoji

# Build rule for target.
codegen_emoji: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_emoji
.PHONY : codegen_emoji

# fast build rule for target.
codegen_emoji/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/build.make Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/build
.PHONY : codegen_emoji/fast

#=============================================================================
# Target rules for targets named codegen_emoji_qmlimportscan

# Build rule for target.
codegen_emoji_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_emoji_qmlimportscan
.PHONY : codegen_emoji_qmlimportscan

# fast build rule for target.
codegen_emoji_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji_qmlimportscan.dir/build.make Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji_qmlimportscan.dir/build
.PHONY : codegen_emoji_qmlimportscan/fast

#=============================================================================
# Target rules for targets named codegen_lang

# Build rule for target.
codegen_lang: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_lang
.PHONY : codegen_lang

# fast build rule for target.
codegen_lang/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/build.make Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/build
.PHONY : codegen_lang/fast

#=============================================================================
# Target rules for targets named codegen_lang_qmlimportscan

# Build rule for target.
codegen_lang_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_lang_qmlimportscan
.PHONY : codegen_lang_qmlimportscan

# fast build rule for target.
codegen_lang_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang_qmlimportscan.dir/build.make Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang_qmlimportscan.dir/build
.PHONY : codegen_lang_qmlimportscan/fast

#=============================================================================
# Target rules for targets named codegen_style

# Build rule for target.
codegen_style: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_style
.PHONY : codegen_style

# fast build rule for target.
codegen_style/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/build.make Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/build
.PHONY : codegen_style/fast

#=============================================================================
# Target rules for targets named codegen_style_qmlimportscan

# Build rule for target.
codegen_style_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_style_qmlimportscan
.PHONY : codegen_style_qmlimportscan

# fast build rule for target.
codegen_style_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/codegen/codegen/style/CMakeFiles/codegen_style_qmlimportscan.dir/build.make Telegram/codegen/codegen/style/CMakeFiles/codegen_style_qmlimportscan.dir/build
.PHONY : codegen_style_qmlimportscan/fast

#=============================================================================
# Target rules for targets named icu_regex_minimal

# Build rule for target.
icu_regex_minimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 icu_regex_minimal
.PHONY : icu_regex_minimal

# fast build rule for target.
icu_regex_minimal/fast:
	$(MAKE) $(MAKESILENT) -f Telegram/lib_icu/CMakeFiles/icu_regex_minimal.dir/build.make Telegram/lib_icu/CMakeFiles/icu_regex_minimal.dir/build
.PHONY : icu_regex_minimal/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Telegram_XdgNotifications_cppgir"
	@echo "... Telegram_XdgNotifications_dbus_timestamp"
	@echo "... Telegram_XdgNotifications_gir"
	@echo "... Telegram_XdpBackground_cppgir"
	@echo "... Telegram_XdpBackground_dbus_timestamp"
	@echo "... Telegram_XdpBackground_gir"
	@echo "... Telegram_appstream_changelog"
	@echo "... Telegram_autogen"
	@echo "... Telegram_autogen_timestamp_deps"
	@echo "... Telegram_qmlimportscan"
	@echo "... codegen_emoji_qmlimportscan"
	@echo "... codegen_lang_qmlimportscan"
	@echo "... codegen_style_qmlimportscan"
	@echo "... examples"
	@echo "... external_cld3_bundled_feature_extractor.proto"
	@echo "... external_cld3_bundled_sentence.proto"
	@echo "... external_cld3_bundled_task_spec.proto"
	@echo "... external_glib_cppgir"
	@echo "... external_qt_static_plugins_fcitx5_autogen"
	@echo "... external_qt_static_plugins_fcitx5_autogen_timestamp_deps"
	@echo "... external_qt_static_plugins_fcitx5_dbusaddons_autogen"
	@echo "... external_qt_static_plugins_fcitx5_dbusaddons_autogen_timestamp_deps"
	@echo "... external_qt_static_plugins_hime_autogen"
	@echo "... external_qt_static_plugins_hime_autogen_timestamp_deps"
	@echo "... external_qt_static_plugins_kimageformats_autogen"
	@echo "... external_qt_static_plugins_kimageformats_autogen_timestamp_deps"
	@echo "... external_qt_static_plugins_nimf_autogen"
	@echo "... external_qt_static_plugins_nimf_autogen_timestamp_deps"
	@echo "... lib_base_Mpris_cppgir"
	@echo "... lib_base_Mpris_dbus_timestamp"
	@echo "... lib_base_Mpris_gir"
	@echo "... lib_base_MutterIdleMonitor_cppgir"
	@echo "... lib_base_MutterIdleMonitor_dbus_timestamp"
	@echo "... lib_base_MutterIdleMonitor_gir"
	@echo "... lib_base_SigxcpuFeedback_cppgir"
	@echo "... lib_base_SigxcpuFeedback_dbus_timestamp"
	@echo "... lib_base_SigxcpuFeedback_gir"
	@echo "... lib_base_Snapcraft_cppgir"
	@echo "... lib_base_Snapcraft_dbus_timestamp"
	@echo "... lib_base_Snapcraft_gir"
	@echo "... lib_base_XdgDBus_cppgir"
	@echo "... lib_base_XdgDBus_dbus_timestamp"
	@echo "... lib_base_XdgDBus_gir"
	@echo "... lib_base_XdgFileManager1_cppgir"
	@echo "... lib_base_XdgFileManager1_dbus_timestamp"
	@echo "... lib_base_XdgFileManager1_gir"
	@echo "... lib_base_XdpInhibit_cppgir"
	@echo "... lib_base_XdpInhibit_dbus_timestamp"
	@echo "... lib_base_XdpInhibit_gir"
	@echo "... lib_base_XdpOpenURI_cppgir"
	@echo "... lib_base_XdpOpenURI_dbus_timestamp"
	@echo "... lib_base_XdpOpenURI_gir"
	@echo "... lib_base_XdpRequest_cppgir"
	@echo "... lib_base_XdpRequest_dbus_timestamp"
	@echo "... lib_base_XdpRequest_gir"
	@echo "... lib_base_XdpSettings_cppgir"
	@echo "... lib_base_XdpSettings_dbus_timestamp"
	@echo "... lib_base_XdpSettings_gir"
	@echo "... lib_ui_autogen"
	@echo "... lib_ui_autogen_timestamp_deps"
	@echo "... lib_ui_emoji"
	@echo "... lib_ui_palette"
	@echo "... lib_ui_styles"
	@echo "... lib_webview_Webview_cppgir"
	@echo "... lib_webview_Webview_dbus_timestamp"
	@echo "... lib_webview_Webview_gir"
	@echo "... td_lang_lang"
	@echo "... td_scheme_scheme"
	@echo "... td_ui_styles"
	@echo "... uninstall"
	@echo "... wrappers"
	@echo "... Telegram"
	@echo "... Telegram_XdgNotifications_dbus"
	@echo "... Telegram_XdpBackground_dbus"
	@echo "... codegen_common"
	@echo "... codegen_emoji"
	@echo "... codegen_lang"
	@echo "... codegen_style"
	@echo "... cppgir"
	@echo "... external_cld3_bundled"
	@echo "... external_kcoreaddons_bundled"
	@echo "... external_qr_code_generator_bundled"
	@echo "... external_qt_static_plugins"
	@echo "... external_qt_static_plugins_fcitx5"
	@echo "... external_qt_static_plugins_fcitx5_dbusaddons"
	@echo "... external_qt_static_plugins_fcitx5_init"
	@echo "... external_qt_static_plugins_hime"
	@echo "... external_qt_static_plugins_hime_im_client"
	@echo "... external_qt_static_plugins_hime_init"
	@echo "... external_qt_static_plugins_kimageformats"
	@echo "... external_qt_static_plugins_kimageformats_init"
	@echo "... external_qt_static_plugins_nimf"
	@echo "... external_qt_static_plugins_nimf_init"
	@echo "... external_rlottie_bundled"
	@echo "... icu_regex_minimal"
	@echo "... lib_base"
	@echo "... lib_base_Mpris_dbus"
	@echo "... lib_base_MutterIdleMonitor_dbus"
	@echo "... lib_base_SigxcpuFeedback_dbus"
	@echo "... lib_base_Snapcraft_dbus"
	@echo "... lib_base_XdgDBus_dbus"
	@echo "... lib_base_XdgFileManager1_dbus"
	@echo "... lib_base_XdpInhibit_dbus"
	@echo "... lib_base_XdpOpenURI_dbus"
	@echo "... lib_base_XdpRequest_dbus"
	@echo "... lib_base_XdpSettings_dbus"
	@echo "... lib_base_crash_report_writer"
	@echo "... lib_crl"
	@echo "... lib_ffmpeg"
	@echo "... lib_lottie"
	@echo "... lib_prisma"
	@echo "... lib_qr"
	@echo "... lib_spellcheck"
	@echo "... lib_storage"
	@echo "... lib_stripe"
	@echo "... lib_tgcalls"
	@echo "... lib_tl"
	@echo "... lib_ui"
	@echo "... lib_webrtc"
	@echo "... lib_webview"
	@echo "... lib_webview_Webview_dbus"
	@echo "... td_export"
	@echo "... td_iv"
	@echo "... td_lang"
	@echo "... td_mtproto"
	@echo "... td_scheme"
	@echo "... td_tde2e"
	@echo "... td_ui"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

